### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by enigma-watcher** [Sorackb/JSinespClient#1]
![screenshot_20180813-101320_sinesp cidadao](https://user-images.githubusercontent.com/42346260/44037244-3c03c3a2-9eea-11e8-9cab-887547f36900.jpg)

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.
